# Generated by Django 4.0 on 2021-12-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0003_alter_post_category_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='users.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
    ]
